# test notification
koalamon_notification_test_notification:
    path:     /p/{project}/notifications/sendtest/{configuration}/
    defaults: { _controller: KoalamonNotificationBundle:Default:sendTestNotification }
    options:
        expose: true


# notification channels
koalamon_notification_home:
    path:     /p/{project}/notifications/
    defaults: { _controller: KoalamonNotificationBundle:Default:index }

koalamon_notification_create:
    path:     /p/{project}/notifications/create/{senderIdentifier}/
    defaults: { _controller: KoalamonNotificationBundle:Default:create }

koalamon_notification_delete:
    path:     /p/{project}/notifications/delete/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationBundle:Default:delete }

koalamon_notification_edit:
    path:     /p/{project}/notifications/edit/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationBundle:Default:edit }

koalamon_notification_store:
    path:     /p/{project}/notifications/store/
    defaults: { _controller: KoalamonNotificationBundle:Default:store }


# alerts
koalamon_notification_alerts_home:
    path:     /p/{project}/alerts/
    defaults: { _controller: KoalamonNotificationBundle:Alerts:index }

koalamon_notification_alerts_edit:
    path:     /p/{project}/edit/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationBundle:Alerts:edit }

koalamon_notification_alerts_store:
    path:     /p/{project}/store/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationBundle:Alerts:store }